### ISSUE TITLE
Is anyone actually using this lib in production?

### ISSUE THREAD

**Issue by sirvon** [Ziggeo/ZiggeoAndroidSDK#3]
Can you confirm that there are Android apps actually using this lib?
b/c update after update this lib is totally unusable with the developer
spending time to fix the lib.....

this is the latest error after updating the lib ....

``` shell
Error:(444, 40) error: method determineClosestSupportedResolution in class VideoQuality cannot be applied to given types;
required: Camera.Parameters,VideoQuality
found: List<Camera.Size>,VideoQuality
reason: actual argument List<Camera.Size> cannot be converted to Camera.Parameters by method invocation conversion
```

**Comment by oliverfriedmann** [comment]
Sounds like you didn't update any submodule dependencies. Try git submodule update...
